[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/pix-payment"
  to = "/.netlify/functions/pix-payment"
  status = 200

[[redirects]]
  from = "/api/pix-status"
  to = "/.netlify/functions/pix-status"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200